/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.16
 * Generated at: 2022-03-07 09:55:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.project.ConnectionProvider;
import java.sql.*;

public final class changeSecurityQuestion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1646646205829L));
    _jspx_dependants.put("/changeDetailsHeader.jsp", Long.valueOf(1644836410000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.project.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/home-style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js'></script>\n");
      out.write("</head>\n");
      out.write(" <!--Header-->\n");
      out.write("<br>\n");
      out.write("<div class=\"topnav sticky\">\n");
      out.write("<center><h2>Change Details<i class=\"fa fa-edit\"></i></h2></center>\n");
String email=session.getAttribute("email").toString(); 
      out.write("\n");
      out.write("<h2><a href=\"home.jsp\"><i class='fas fa-arrow-circle-left'>Back</i></a></h2>\n");
      out.write("<h2><a href=\"\">Your Profile(");
      out.print(email);
      out.write(") <i class='fas fa-user-alt'></i></a></h2>\n");
      out.write("<a href=\"changePassword.jsp\">Change Password <i class='fas fa-key'></i></a>\n");
      out.write("<a href=\"addChangeAddress.jsp\">Add or change Address <i class='fas fa-map-marker-alt'></i></a>\n");
      out.write("<a href=\"changeSecurityQuestion.jsp\">Change Security Question <i class=\"fa fa-repeat\"></i></a>\n");
      out.write("<a href=\"changeMobileNumber.jsp\">Change Mobile Number <i class='fas fa-phone'></i></a>\n");
      out.write("</div>\n");
      out.write("<br>\n");
      out.write("<!--table-->\n");
      out.write('\n');
      out.write(" <div class=\"footer\">\n");
      out.write("          <p>All Right Reserved @ Javeriya 2022</p>\n");
      out.write("      </div>");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changeDetails.css\">\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js'></script>\n");
      out.write("<title>Change Security Question</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");

String msg=request.getParameter("msg");
if("done".equals(msg))
{

      out.write("\n");
      out.write("<h3 class=\"alert\">Your security Question successfully changed !</h3>\n");

}

      out.write('\n');

if("wrong".equals(msg))
{

      out.write("\n");
      out.write("<h3 class=\"alert\">Your Password is wrong!</h3>\n");

}

      out.write("\n");
      out.write("<form action=\"changeSecurityQuestionAction.jsp\" method=\"post\">\n");
      out.write("<h3>Select Your New Security Question</h3>\n");
      out.write("<select class=\"input-style\" name=\"securityQuestion\" required>\n");
      out.write("<option value=\"What is the name of your first pet ?\">What is the name of your first pet ?</option>\n");
      out.write("<option value=\"What is your first car ?\">What is your first car ?</option>\n");
      out.write("<option value=\"Where did you born ?\">Where did you born ?</option>\n");
      out.write("<option value=\"What is the name of your first school ?\">What is the name of your first school ?</option>\n");
      out.write(" </select>\n");
      out.write(" <hr>\n");
      out.write(" <h3>Enter Your New Answer</h3>\n");
      out.write(" <input class=\"input-style\" type=\"text\" name=\"newAnswer\" placeholder=\"new answer\" required>\n");
      out.write("<hr>\n");
      out.write("<h3>Enter Password (For Security)</h3>\n");
      out.write(" <input class=\"input-style\" type=\"password\" name=\"password\" placeholder=\"password\" required>\n");
      out.write("<hr>\n");
      out.write(" <button class=\"button\" type=\"submit\">Save <i class='far fa-arrow-alt-circle-right'></i></button>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("<br><br><br>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
